[package]
name = "chgrp"
version = "0.0.1"
authors = []

[lib]
name = "uu_chgrp"
path = "chgrp.rs"

[dependencies]
getopts = "*"
libc = "*"
aho-corasick = "*"
memchr = "*"
regex = "*"
regex-syntax = "*"
uucore = { path="../uucore" }
walker = "*"

[[bin]]
name = "chgrp"
path = "main.rs"
